version: '3.8'

services:
  backend-python:
    image: goldflow/aquarag-backend-python:latest
    container_name: backend-python
    ports:
      - "8000:8000"
    networks:
      - aquarag-net

  backend-java:
    image: goldflow/aquarag-backend-java:latest
    container_name: backend-java
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - aquarag-net

  frontend:
    image: goldflow/aquarag-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - aquarag-net

networks:
  aquarag-net:
    driver: bridge