apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aquarag-secrets
                  key: aws-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aquarag-secrets
                  key: aws-key
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aquarag-secrets
                  key: google-key
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aquarag-secrets
                  key: pinecone-key
            - name: AWS_REGION
              value: us-east-2
            - name: AWS_S3_BUCKET
              value: aqua-rag-135808918878-us-east-2-an
            - name: PINECONE_INDEX_NAME
              value: aqua-rag
            - name: RABBITMQ_HOST
              value: rabbitmq
            # 👇 核心修复：告诉代码里的 requests 跨越 Pod 去内网呼叫 FastAPI 网页服务名
            - name: PYTHON_BACKEND_HOST
              value: backend-python
          # 💡 核心优化：直接复用你本地已经打好的 python 算法镜像，不单独打包 worker 镜像
          image: goldflow/aquarag-backend-python:latest
          imagePullPolicy: IfNotPresent
          name: aquarag-worker
          # 👇 核心优化：强行覆盖默认镜像入口，告诉这个容器专门运行你的后台消费者脚本
          command: ["python", "worker.py"] # ⚠️ 如果你本地的消费者脚本不叫 worker.py，请将这里换成真实的脚本文件名
      restartPolicy: Always