import os
import subprocess
import requests

def create_pr(issue_key, title_summary):
    """
    Automatically pushes the current branch and creates a GitHub Pull Request.
    """
    try:
        # 1. Get current branch name
        branch_name = subprocess.check_output(["git", "branch", "--show-current"], text=True).strip()
        print(f"📡 Current branch detected: {branch_name}")
        
        # 2. Push the branch to remote repository
        print(f"🚀 Pushing branch {branch_name} to origin...")
        subprocess.run(["git", "push", "-u", "origin", branch_name], check=True)
        
        # 3. Read GitHub Config from Environment Variables
        GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
        REPO_OWNER = os.getenv("GITHUB_OWNER")      
        REPO_NAME = os.getenv("GITHUB_REPO")        
        
        if not all([GITHUB_TOKEN, REPO_OWNER, REPO_NAME]):
            print("⚠ Warning: Missing GitHub environment variables. Skipping PR creation.")
            return None

        # 4. Construct PR API Payload
        url = f"https://github.com{REPO_OWNER}/{REPO_NAME}/pulls"
        headers = {
            "Authorization": f"token {GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json"
        }
        payload = {
            "title": f"[{issue_key}] {title_summary}",
            "head": branch_name,
            "base": "main",  # Target branch
            "body": f"### JIRA Ticket\nFixes {issue_key}\n\n### Summary\nThis PR was automatically generated by the AquaRAG Automation Agent.",
            "draft": False
        }

        # 5. Send POST Request to GitHub
        response = requests.post(url, json=payload, headers=headers)
        if response.status_code == 201:
            pr_url = response.json().get("html_url")
            print(f"✅ Pull Request successfully created: {pr_url}")
            return pr_url
        else:
            print(f"❌ Failed to create PR. Status Code: {response.status_code}")
            print(response.text)
            return None
            
    except Exception as e:
        print(f"❌ Error during PR workflow: {e}")
        return None
