import os
import subprocess
import requests

def create_pr(issue_key, title_summary):
    """
    只负责调用 GitHub API 创建 Pull Request（不重复做 git push）
    """
    try:
        # 1. 动态获取当前分支名（用来告诉 GitHub 哪条分支要发起合并）
        branch_name = subprocess.check_output(["git", "branch", "--show-current"], text=True).strip()
        print(f"📡 Current branch detected: {branch_name}")
        
        # 2. 从环境变量读取 GitHub 配置
        GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
        REPO_OWNER = os.getenv("GITHUB_OWNER")      
        REPO_NAME = os.getenv("GITHUB_REPO")        
        
        if not all([GITHUB_TOKEN, REPO_OWNER, REPO_NAME]):
            print("⚠ Warning: Missing GitHub environment variables. Skipping PR creation.")
            return None

        # 3. 构造正确的 GitHub API 终结点 (已修正 URL)
        url = f"https://github.com{REPO_OWNER}/{REPO_NAME}/pulls"
        headers = {
            "Authorization": f"token {GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json"
        }
        payload = {
            "title": f"[{issue_key}] {title_summary}",
            "head": branch_name, # 目标源分支
            "base": "main",      # 想要合并到的目标主分支
            "body": f"### JIRA Ticket\nFixes {issue_key}\n\n### Summary\nThis PR was automatically generated by the AquaRAG Automation Agent.",
            "draft": False
        }

        # 4. 发送 POST 请求创建 PR
        response = requests.post(url, json=payload, headers=headers)
        if response.status_code == 201:
            pr_url = response.json().get("html_url")
            print(f"✅ Pull Request successfully created: {pr_url}")
            return pr_url
        else:
            print(f"❌ Failed to create PR. Status Code: {response.status_code}")
            print(response.text)
            return None
            
    except Exception as e:
        print(f"❌ Error during PR workflow: {e}")
        return None

