import os
import subprocess
import requests

def create_pr(issue_key, title_summary):
    """
    调用 GitHub REST API 创建 Pull Request（已补全防火墙所需的安全头字段）
    """
    try:
        # 1. 动态获取当前分支名
        branch_name = subprocess.check_output(["git", "branch", "--show-current"], text=True).strip()
        print(f"📡 Current branch detected: {branch_name}")

        # 2. 从环境变量读取 GitHub 核心配置
        GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
        REPO_OWNER = os.getenv("GITHUB_OWNER")      # 应为 "chenhappy1"
        REPO_NAME = os.getenv("GITHUB_REPO")        # 应为 "AquaRAG"

        if not all([GITHUB_TOKEN, REPO_OWNER, REPO_NAME]):
            print("⚠ Warning: Missing GitHub environment variables. Skipping PR creation.")
            return None

        # 3. 官方标准的 API 终结点 URL 路径
        url = f"https://github.com/{REPO_OWNER}/{REPO_NAME}/pulls"
        
        # ✨【核心防护修复】加入必要的 User-Agent 标头，绕过 GitHub 防火墙的 422 阻断
        headers = {
            "Authorization": f"token {GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "AquaRAG-Automation-Agent/1.0 (Python Requests)"
        }
        
        payload = {
            "title": f"[{issue_key}] {title_summary}",
            "head": branch_name,  # 开发源分支（如 feature/SCRUM-6）
            "base": "main",       # 目标合并主分支
            "body": f"### JIRA Ticket\nFixes {issue_key}\n\n### Summary\nThis PR was automatically generated by the AquaRAG Automation Agent.",
            "draft": False
        }

        # 4. 发送 POST 请求创建 PR
        print(f"📡 Requesting GitHub API: {url}")
        response = requests.post(url, json=payload, headers=headers)
        
        if response.status_code == 201:
            pr_url = response.json().get("html_url")
            print(f"✅ Pull Request successfully created: {pr_url}")
            return pr_url
        else:
            print(f"❌ Failed to create PR. Status Code: {response.status_code}")
            print("=" * 50)
            print("🔍 GitHub Response Text Preview:")
            print(response.text[:1000])  # 只打印前1000个字符防止撑爆终端
            print("=" * 50)
            return None
            
    except Exception as e:
        print(f"❌ Error during PR workflow: {e}")
        return None