spring.application.name=backend
server.port=9000
jdbc:postgresql://daqua-postgres.c9eq6ois239k.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=MyStrongPassword123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 自动建表（可选）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true